version: '2'

services:
        management-ui:
            image: digitalshoestring/job_locations_batch_ui:v1.0.0 
            working_dir: /app
            command: sh -c "python manage.py collectstatic --noinput &&
                                python manage.py migrate &&
                                daphne -b 0.0.0.0 -p 80 management_portal.asgi:application"
            volumes:
                        - ./dashboard/data/:/app/data
                        - ./dashboard/config/:/app/config
                        - /etc/localtime:/etc/localtime:ro
            ports:
                        - "80:80"
            networks:
                        internal:
                                aliases:
                                        - management-ui.docker.local
            logging:
                    driver: syslog
                    options:
                            tag: docker-management-ui
            restart: unless-stopped

        job-db:
            image: digitalshoestring/job_locations_batch_sds:v1.0.0
            working_dir: /app
            command: sh -c "python manage.py collectstatic --noinput &&
                                python manage.py migrate &&
                                daphne -b 0.0.0.0 -p 80 job_locations.asgi:application"
            volumes:
                - ./db/data/:/app/data
                - /etc/localtime:/etc/localtime:ro
            ports:
                - "8001:80"
            networks:
                internal:
                    aliases:
                        - job-db.docker.local
            logging:
                    driver: syslog
                    options:
                            tag: docker-job-db
            restart: unless-stopped

        user-input:
            image: digitalshoestring/user_input_barcode_dc:v1.0.0
            working_dir: /app
            command: sh -c "python manage.py collectstatic --noinput &&
                                python manage.py migrate &&
                                daphne -b 0.0.0.0 -p 80 site_config.asgi:application"
            volumes:
                - ./user_input/config/:/app/static/config/
                                #- /etc/localtime:/etc/localtime:ro
            ports:
                - "8080:80"
            networks:
                internal:
                    aliases:
                        - user-input.docker.local
            logging:
                    driver: syslog
                    options:
                            tag: docker-user-input
            restart: unless-stopped
        
        barcode:
            image: digitalshoestring/barcode_dc:v2.0.0
            privileged: true
            working_dir: /app
            command: "python main.py"
            devices:
                - /dev/input:/dev/input:ro
            volumes:
                - ./barcode/config.toml:/app/config.toml
                - /etc/localtime:/etc/localtime:ro
                - /run/udev:/run/udev:ro
            networks:
                internal:
                    aliases:
                        - bs.docker.local
            logging:
                driver: syslog
                options:
                    tag: docker-barcode
            restart: unless-stopped

        mosquitto:
            extends:
                file: mosquitto/app.yml
                service: app
            ports:
                - "8883:8883"
            networks:
                internal:
                    aliases:
                        - mqtt.docker.local
            logging:
                    driver: syslog
                    options:
                            tag: docker-mosquitto
            restart: unless-stopped


networks:
        internal:
